PROJECT=report
PROJECT_NAME=report
PROJECT_VERSION=20141005
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=BSD
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2014
PROJECT_DESCRIPTION=report
PROJECT_WEBSITE=https://github.com/jdkoftinoff/report
PROJECT_IDENTIFIER=com.jdkoftinoff.report
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=

CXXFLAGS+=-std=c++11 

